In [1]:
import numpy as np

In [2]:
a=[1,2,3]
np.array(a)

array([1, 2, 3])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
b=[1,2,3],[3,4,5],[6,7,8]
np.array(b)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.arange(1,5)

array([1, 2, 3, 4])

In [7]:
np.arange(1,90)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89])

In [21]:
np.arange(1,2,5)

array([1])

In [22]:
np.arange(1,5,2)

array([1, 3])

In [23]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [24]:
np.arange(1,5,1)

array([1, 2, 3, 4])

In [8]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(8,int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones((2,4,int))

TypeError: 'type' object cannot be interpreted as an integer

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(0,1,2)

array([0., 1.])

In [18]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [19]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(1,10,2)

array([ 1., 10.])

In [26]:
np.eye(3,int)

TypeError: 'type' object cannot be interpreted as an integer

In [27]:
np.eye(3,datatype=int)

TypeError: eye() got an unexpected keyword argument 'datatype'

In [29]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
np.random.rand(2,4)##2=row,4=col

array([[0.7368676 , 0.7158279 , 0.23480716, 0.52995381],
       [0.87148677, 0.1166056 , 0.76391087, 0.2100125 ]])

In [34]:
np.random.rand(5,5)

array([[0.25107857, 0.68832145, 0.66702238, 0.69245716, 0.08551898],
       [0.49866164, 0.38619619, 0.13741667, 0.60008444, 0.97842953],
       [0.21604621, 0.46120298, 0.13691868, 0.01059219, 0.36658096],
       [0.62437773, 0.61831597, 0.35500357, 0.13395242, 0.86124382],
       [0.04747497, 0.15789829, 0.65120577, 0.02718093, 0.78357489]])

In [32]:
np.random.randn(2,4)## if we put n it ll take both +ve as well as -ve values randomly

array([[ 0.77704345,  0.71148231, -1.08095988,  0.84513024],
       [-0.18510627, -0.66780628, -0.26054973,  1.24841552]])

In [33]:
np.random.randn(5,5)

array([[-0.63187741,  0.58028436,  1.03998938, -0.78947886, -0.2568736 ],
       [ 0.25080755,  0.67078217,  0.25194017, -0.24674458,  1.13604537],
       [-0.84033602,  0.55687016, -0.60588292,  1.21062296,  0.44660262],
       [ 0.50619402, -1.23780552,  0.47689857,  0.19407166, -0.43993286],
       [ 0.95916281, -1.38159958,  1.8595029 ,  1.16235331, -1.67342863]])

In [47]:
np.random.randn(3,5,2)

array([[[ 0.28667343,  1.98621362],
        [ 0.98458782, -0.8799228 ],
        [-1.65494984, -0.39272529],
        [-0.80502909, -0.02075741],
        [-1.19380849,  0.29351964]],

       [[-1.54026401, -0.11159547],
        [-1.69189568,  0.9445237 ],
        [-0.45917171, -0.53109673],
        [ 0.13046084, -0.30696099],
        [ 1.89588452,  0.64054548]],

       [[ 0.9677026 ,  0.52858191],
        [-0.11216314,  0.78795433],
        [-1.03926058,  0.12696864],
        [-0.69813118,  0.44297823],
        [ 1.55498932, -0.18981768]]])

In [45]:
np.random.rand(3,5,2)

array([[[0.9704263 , 0.99176257],
        [0.02434019, 0.92808357],
        [0.8358427 , 0.54446011],
        [0.59763209, 0.17854574],
        [0.0283999 , 0.91914852]],

       [[0.70683782, 0.91213727],
        [0.8939802 , 0.84870407],
        [0.08532525, 0.26487018],
        [0.22422167, 0.84034221],
        [0.44120807, 0.13380261]],

       [[0.96144369, 0.44835299],
        [0.11813407, 0.08872832],
        [0.8304743 , 0.67914159],
        [0.87609477, 0.17904268],
        [0.19934048, 0.55086126]]])

In [35]:
np.random.randint(1,10,25)##between 1to 10 randomly it ll give 25 num

array([9, 8, 6, 9, 6, 3, 5, 7, 2, 1, 5, 4, 3, 1, 3, 1, 8, 9, 9, 9, 5, 5,
       1, 5, 8])

In [36]:
np.random.randint(1,10,10)

array([7, 5, 2, 4, 1, 6, 8, 1, 2, 9])

In [37]:
np.random.randint(1,100,25)

array([94, 36, 61, 12, 59, 18, 33, 76, 40,  4, 22,  8, 22, 38, 18, 29, 30,
       96, 13, 89, 66, 59, 90, 51, 28])

In [38]:
np.random.randint(1,100,55)

array([80, 77,  6, 48, 13,  6, 15, 52, 61, 48, 34, 98, 17, 39, 38, 17,  5,
        8, 47, 91, 15, 53, 48, 12, 90, 56,  9, 13, 34, 47,  3, 90, 73, 23,
       62, 99, 34, 41, 70, 95, 89, 41,  9, 35, 41, 28, 82,  9, 67, 95, 74,
       74, 64,  6, 93])

In [41]:
a=np.arange(2,20)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [60]:
a.min()

AttributeError: 'list' object has no attribute 'min'

In [50]:
h=np.random.randint(1,100,25)
h

array([22, 68, 96, 37, 62, 66, 11, 48,  9, 83, 25, 14, 88, 97, 97, 38, 62,
       74, 47, 86, 77, 51, 85, 14, 94])

In [58]:
h.min()

9

In [65]:
h.max()

97

In [68]:
h.argmin()##returns the index of the min value

8

In [69]:
h.argmax()

13

In [71]:
h.dtype

dtype('int32')

In [75]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
a=np.random.rand(2,3)
a

array([[0.66137724, 0.33840641, 0.75342063],
       [0.9943865 , 0.2588078 , 0.06304766]])

In [78]:
a.T ##T=transpose:shift row to col,col to row

array([[0.66137724, 0.9943865 ],
       [0.33840641, 0.2588078 ],
       [0.75342063, 0.06304766]])

In [82]:
a=np.arange(10,28)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [83]:
a=a.reshape(6,3)##reshape:arrange that num to rows and columns
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [84]:
a.reshape(9,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [85]:
a.reshape(3,4)

ValueError: cannot reshape array of size 18 into shape (3,4)

In [86]:
a[2]=100
a

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [100, 100, 100],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [ 25,  26,  27]])

In [88]:
a[0]=1
a

array([[  1,   1,   1],
       [ 13,  14,  15],
       [100, 100, 100],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [ 25,  26,  27]])

In [89]:
a[4:7]

array([[22, 23, 24],
       [25, 26, 27]])

In [91]:
a[1:2]

array([[13, 14, 15]])

In [92]:
a[0:5]

array([[  1,   1,   1],
       [ 13,  14,  15],
       [100, 100, 100],
       [ 19,  20,  21],
       [ 22,  23,  24]])

In [93]:
a[0:6]

array([[  1,   1,   1],
       [ 13,  14,  15],
       [100, 100, 100],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [ 25,  26,  27]])

In [94]:
a[ :3]

array([[  1,   1,   1],
       [ 13,  14,  15],
       [100, 100, 100]])

In [95]:
a[0:]

array([[  1,   1,   1],
       [ 13,  14,  15],
       [100, 100, 100],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [ 25,  26,  27]])

In [107]:
a[0:6]=1
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [109]:
a[1:3]=3
a

array([[1, 1, 1],
       [3, 3, 3],
       [3, 3, 3],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [111]:
a=np.array([[1,2,3],[4,5,6],[9,6,7],[2,3,4]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [9, 6, 7],
       [2, 3, 4]])

In [113]:
a[1,2]

6

In [114]:
a[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [116]:
a[1][2]

6

In [117]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
a[2:]

array([[9, 6, 7],
       [2, 3, 4]])

In [120]:
a[1:3,0:3]##1:3=row i.e1,2   0:3=col i.e o,1,2

array([[4, 5, 6],
       [9, 6, 7]])

In [121]:
a[0:2,1:2]

array([[2],
       [5]])

In [122]:
a[1:,2:]

array([[6],
       [7],
       [4]])

In [123]:
a[2]

array([9, 6, 7])

In [125]:
a[:,(2,2)]

array([[3, 3],
       [6, 6],
       [7, 7],
       [4, 4]])

In [126]:
a[:,(1,2)]

array([[2, 3],
       [5, 6],
       [6, 7],
       [3, 4]])

In [127]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [131]:
a+a

array([ 2,  4,  6,  8, 10])

In [132]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [133]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [134]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [135]:
np.max(a)

5

In [137]:
np.argmax(a)

4

In [138]:
np.min(a)

1

In [139]:
np.argmin(a)

0

In [140]:
np.square(a)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [141]:
np.std(a)

1.4142135623730951

In [142]:
np.var(a)

2.0

In [143]:
np.mean(a)

3.0

In [146]:
a=np.random.randn(2,4)
a

array([[-1.69998213,  0.72158609,  0.06154717, -0.34606973],
       [-0.83474498, -1.46458936,  0.15340013,  0.7483155 ]])

In [147]:
np.round(a,2) ##round up to 2 decimals

array([[-1.7 ,  0.72,  0.06, -0.35],
       [-0.83, -1.46,  0.15,  0.75]])

In [148]:
np.round(a,4)

array([[-1.7   ,  0.7216,  0.0615, -0.3461],
       [-0.8347, -1.4646,  0.1534,  0.7483]])

In [149]:
a=np.array(["d","a","q","b"])
np.unique(a)

array(['a', 'b', 'd', 'q'], dtype='<U1')

In [150]:
a=np.array(["dgye","htrd","aeq","ohb"])
np.unique(a)

array(['aeq', 'dgye', 'htrd', 'ohb'], dtype='<U4')